Repository Monofyi/Mobile, pull requests merged in 2021-08, with the labels that each got.

#44 Owner subscribe
  assets/images/Celebration.png
  assets/images/activation_key.svg
  lib/config/constants/app_urls.dart
  lib/config/routes/router.dart
  lib/l10n/app_en.arb
  lib/modules/owner_subscription/bloc/owner_subscription_bloc.dart
  lib/modules/owner_subscription/bloc/owner_subscription_state.dart
  lib/modules/owner_subscription/models/owner_subscription_request.dart
  lib/modules/owner_subscription/models/owner_subscription_response.dart
  lib/modules/owner_subscription/providers/owner_subscription_provider.dart
  lib/modules/owner_subscription/repositories/owner_subscription_repository.dart
  lib/modules/owner_subscription/screens/owner_subscription.dart
  lib/modules/sign_in/cubit/siginin_cubit.dart
  lib/modules/sign_in/screens/owner_not_subscribed.dart
  lib/modules/sign_in/screens/sign_in.dart
  lib/modules/splash_screen/screens/splash_screen.dart
  lib/modules/verify_email/screens/verify_email.dart
  lib/widgets/successfully_completed.dart
Labels: enhancement, flutter

#45 UI Fix
  lib/modules/sign_in/screens/email_not_verified.dart
  lib/modules/sign_in/screens/owner_not_subscribed.dart
Labels: bug, flutter

#50 View supplier
  assets/images/celebration.svg
  assets/images/delete.svg
  assets/images/logo.svg
  assets/images/party_hat.svg
  lib/config/constants/app_urls.dart
  lib/config/routes/router.dart
  lib/config/themes/theme.dart
  lib/config/utils/extensions/response_extension.dart
  lib/modules/home/screens/home.dart
  lib/modules/owner_subscription/screens/owner_subscription.dart
  lib/modules/sign_in/screens/sign_in.dart
  lib/modules/sign_up/components/sign_up_wrapper.dart
  lib/modules/splash_screen/screens/splash_screen.dart
  lib/modules/suppliers/bloc/supplier_bloc.dart
  lib/modules/suppliers/bloc/supplier_state.dart
  lib/modules/suppliers/models/get_suppliers_response.dart
  lib/modules/suppliers/models/supplier.dart
  lib/modules/suppliers/providers/supplier_provider.dart
  lib/modules/suppliers/repositories/supplier_repository.dart
  lib/modules/suppliers/screens/suppliers_list.dart
  lib/modules/suppliers/screens/view_supplier.dart
  lib/modules/verify_email/screens/verify_email.dart
  lib/modules/worker_initialize/screens/worker_initialize.dart
  lib/utils/dev_utils/random_string.dart
  lib/widgets/block_button.dart
  lib/widgets/gradient_button.dart
  lib/widgets/listing.dart
  lib/widgets/required_field_label.dart
  lib/widgets/underlined_title.dart
Labels: enhancement, flutter

#55 Device details
  assets/images/astronaut_flag.svg
  assets/images/cloud_check.svg
  lib/config/constants/app_urls.dart
  lib/config/routes/router.dart
  lib/config/themes/theme.dart
  lib/config/utils/extensions/map_extension.dart
  lib/core/authentication/bloc/authentication_bloc.dart
  lib/core/common/components/action_button.dart
  lib/core/common/components/block_button.dart
  lib/core/common/components/custom_back_button.dart
  lib/core/common/components/form_field_decoration.dart
  lib/core/common/components/gradient_button.dart
  lib/core/common/components/gradient_widget.dart
  lib/core/common/components/required_field_label.dart
  lib/core/common/components/rounded_wide_button.dart
  lib/core/common/components/snackbar_message.dart
  lib/core/common/components/underlined_title.dart
  lib/core/common/models/device_details_request.dart
  lib/core/common/models/device_details_response.dart
  lib/core/common/providers/common_provider.dart
  lib/core/common/repositories/common_repository.dart
  lib/core/common/screens/confirm_operation.dart
  lib/core/common/screens/listing.dart
  lib/core/common/screens/operation_notification.dart
  lib/l10n/app_en.arb
  lib/modules/home/screens/home.dart
  lib/modules/owner_subscription/screens/owner_subscription.dart
  lib/modules/sign_in/screens/email_not_verified.dart
  lib/modules/sign_in/screens/owner_not_subscribed.dart
  lib/modules/sign_in/screens/sign_in.dart
  lib/modules/sign_up/components/sign_up_wrapper.dart
  lib/modules/sign_up/screens/sign_up_one.dart
  lib/modules/sign_up/screens/sign_up_two.dart
  lib/modules/splash_screen/screens/splash_screen.dart
  lib/modules/suppliers/bloc/supplier_bloc.dart
  lib/modules/suppliers/bloc/supplier_list_bloc.dart
  lib/modules/suppliers/bloc/supplier_list_state.dart
  lib/modules/suppliers/bloc/supplier_state.dart
  lib/modules/suppliers/components/supplier_form.dart
  lib/modules/suppliers/models/add_supplier_request.dart
  lib/modules/suppliers/models/add_supplier_response.dart
  lib/modules/suppliers/providers/supplier_provider.dart
  lib/modules/suppliers/repositories/supplier_repository.dart
  lib/modules/suppliers/screens/add_supplier.dart
  lib/modules/suppliers/screens/suppliers_list.dart
  lib/modules/suppliers/screens/view_supplier.dart
  lib/modules/verify_email/screens/verify_email.dart
  lib/modules/worker_initialize/screens/worker_initialize.dart
  lib/widgets/listing.dart
  lib/widgets/successfully_completed.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, flutter

#63 Edit Supplier
  assets/images/change_confirmation.svg
  assets/images/circle_check.svg
  lib/config/constants/app_urls.dart
  lib/core/common/screens/confirm_operation.dart
  lib/l10n/app_en.arb
  lib/modules/suppliers/bloc/supplier_bloc.dart
  lib/modules/suppliers/bloc/supplier_state.dart
  lib/modules/suppliers/components/supplier_form.dart
  lib/modules/suppliers/models/edit_supplier_request.dart
  lib/modules/suppliers/models/edit_supplier_response.dart
  lib/modules/suppliers/providers/supplier_provider.dart
  lib/modules/suppliers/repositories/supplier_repository.dart
  lib/modules/suppliers/screens/add_supplier.dart
  lib/modules/suppliers/screens/suppliers_list.dart
  lib/modules/suppliers/screens/view_supplier.dart
Labels: enhancement, flutter

#68 Delete Supplier
  assets/images/circle_delete.svg
  lib/config/constants/app_urls.dart
  lib/core/authentication/bloc/authentication_bloc.dart
  lib/core/authentication/bloc/authentication_state.dart
  lib/core/common/models/user.dart
  lib/core/common/repositories/common_repository.dart
  lib/core/common/screens/confirm_operation.dart
  lib/core/common/screens/listing.dart
  lib/l10n/app_en.arb
  lib/modules/sign_in/cubit/siginin_cubit.dart
  lib/modules/sign_in/cubit/signin_state.dart
  lib/modules/sign_in/screens/sign_in.dart
  lib/modules/sign_up/bloc/sign_up_bloc.dart
  lib/modules/sign_up/screens/sign_up_one.dart
  lib/modules/splash_screen/screens/splash_screen.dart
  lib/modules/suppliers/bloc/supplier_bloc.dart
  lib/modules/suppliers/components/supplier_form.dart
  lib/modules/suppliers/models/delete_supplier_request.dart
  lib/modules/suppliers/models/delete_supplier_response.dart
  lib/modules/suppliers/providers/supplier_provider.dart
  lib/modules/suppliers/repositories/supplier_repository.dart
  lib/modules/suppliers/screens/add_supplier.dart
  lib/modules/suppliers/screens/suppliers_list.dart
  lib/modules/suppliers/screens/view_supplier.dart
Labels: enhancement, flutter

#107 Listing
  lib/config/routes/route_names.dart
  lib/config/routes/router.dart
  lib/modules/home/screens/home.dart
  lib/modules/owner_subscription/screens/owner_subscription.dart
  lib/modules/sign_in/screens/email_not_verified.dart
  lib/modules/sign_in/screens/owner_not_subscribed.dart
  lib/modules/sign_in/screens/sign_in.dart
  lib/modules/sign_up/screens/sign_up_two.dart
  lib/modules/splash_screen/screens/splash_screen.dart
  lib/modules/suppliers/bloc/supplier_bloc.dart
  lib/modules/suppliers/bloc/supplier_list_bloc.dart
  lib/modules/suppliers/models/get_suppliers_response.dart
  lib/modules/suppliers/screens/add_supplier.dart
  lib/modules/suppliers/screens/suppliers_list.dart
  lib/modules/suppliers/screens/view_supplier.dart
  lib/modules/verify_email/screens/verify_email.dart
  lib/modules/worker_initialize/screens/worker_initialize.dart
Labels: bug, flutter

#108 Home
  assets/images/addToList.svg
  assets/images/factory.svg
  assets/images/home.svg
  assets/images/logout.svg
  assets/images/menu.svg
  assets/images/shipment.svg
  assets/images/support.svg
  lib/config/routes/router.dart
  lib/config/themes/theme.dart
  lib/core/authentication/bloc/authentication_bloc.dart
  lib/core/common/components/sized_cpi.dart
  lib/core/common/screens/confirm_operation.dart
  lib/l10n/app_en.arb
  lib/modules/home/screens/home.dart
  lib/modules/home/screens/home_menu.dart
  lib/modules/home/screens/page_selector.dart
  lib/modules/owner_subscription/screens/owner_subscription.dart
  lib/modules/sign_in/screens/email_not_verified.dart
  lib/modules/sign_in/screens/owner_not_subscribed.dart
  lib/modules/sign_in/screens/sign_in.dart
  lib/modules/sign_up/screens/sign_up_two.dart
  lib/modules/splash_screen/screens/splash_screen.dart
  lib/modules/suppliers/bloc/supplier_bloc.dart
  lib/modules/suppliers/screens/add_supplier.dart
  lib/modules/suppliers/screens/view_supplier.dart
  lib/modules/verify_email/screens/verify_email.dart
  lib/modules/worker_initialize/screens/worker_initialize.dart
  lib/utils/dev_utils/random_quantity.dart
  lib/utils/dev_utils/random_string.dart
Labels: bug, enhancement, flutter

#111 Workers
  lib/config/constants/app_urls.dart
  lib/config/routes/route_names.dart
  lib/config/routes/router.dart
  lib/config/themes/theme.dart
  lib/core/common/components/block_button.dart
  lib/core/common/components/sized_cpi.dart
  lib/core/common/screens/confirm_operation.dart
  lib/l10n/app_en.arb
  lib/modules/home/screens/home.dart
  lib/modules/home/screens/home_menu.dart
  lib/modules/home/screens/page_selector.dart
  lib/modules/sign_in/screens/sign_in.dart
  lib/modules/sign_up/screens/sign_up_two.dart
  lib/modules/suppliers/components/supplier_form.dart
  lib/modules/suppliers/screens/view_supplier.dart
  lib/modules/verify_email/screens/verify_email.dart
  lib/modules/worker_initialize/screens/worker_initialize.dart
  lib/modules/workers/bloc/worker_bloc.dart
  lib/modules/workers/bloc/worker_list_bloc.dart
  lib/modules/workers/bloc/worker_list_state.dart
  lib/modules/workers/bloc/worker_state.dart
  lib/modules/workers/models/delete_worker_request.dart
  lib/modules/workers/models/delete_worker_response.dart
  lib/modules/workers/models/get_workers_response.dart
  lib/modules/workers/models/worker.dart
  lib/modules/workers/providers/worker_provider.dart
  lib/modules/workers/repositories/worker_repository.dart
  lib/modules/workers/screens/view_worker.dart
  lib/modules/workers/screens/workers_list.dart
  lib/utils/dev_utils/random_quantity.dart
Labels: bug, enhancement, flutter

#112 Network Check
  assets/images/headphoneBall.svg
  assets/images/noNetwork.svg
  lib/config/routes/route_names.dart
  lib/config/routes/router.dart
  lib/core/authentication/bloc/authentication_bloc.dart
  lib/core/common/providers/common_provider.dart
  lib/core/common/screens/no_network.dart
  lib/core/network/bloc/network_bloc.dart
  lib/core/network/bloc/network_state.dart
  lib/l10n/app_en.arb
  lib/main.dart
  pubspec.lock
  pubspec.yaml
  test/logic/authentication/authentication_bloc_test.dart
Labels: enhancement, flutter

#115 Buyer
  lib/config/constants/app_urls.dart
  lib/config/routes/route_names.dart
  lib/config/routes/router.dart
  lib/l10n/app_en.arb
  lib/modules/buyers/bloc/buyer_bloc.dart
  lib/modules/buyers/bloc/buyer_list_bloc.dart
  lib/modules/buyers/bloc/buyer_list_state.dart
  lib/modules/buyers/bloc/buyer_state.dart
  lib/modules/buyers/components/buyer_form.dart
  lib/modules/buyers/models/add_buyer_request.dart
  lib/modules/buyers/models/add_buyer_response.dart
  lib/modules/buyers/models/buyer.dart
  lib/modules/buyers/models/delete_buyer_request.dart
  lib/modules/buyers/models/delete_buyer_response.dart
  lib/modules/buyers/models/edit_buyer_request.dart
  lib/modules/buyers/models/edit_buyer_response.dart
  lib/modules/buyers/models/get_buyer_response.dart
  lib/modules/buyers/providers/buyer_provider.dart
  lib/modules/buyers/repositories/buyer_repository.dart
  lib/modules/buyers/screens/add_buyers.dart
  lib/modules/buyers/screens/buyers_list.dart
  lib/modules/buyers/screens/view_buyers.dart
  lib/modules/home/screens/home.dart
Labels: enhancement, flutter
