Repository Monofyi/Mobile, pull requests merged in 2021-07, with the labels that each got.

#14 Splash Screen
  README.md
  assets/fonts/Poppins-Bold.ttf
  assets/fonts/Poppins-BoldItalic.ttf
  assets/fonts/Poppins-Italic.ttf
  assets/fonts/Poppins-Regular.ttf
  assets/fonts/Righteous-Regular.ttf
  assets/images/logo.png
  lib/config/router.dart
  lib/config/theme.dart
  lib/data/account_repository.dart
  lib/logic/authentication/authentication_bloc.dart
  lib/logic/authentication/authentication_state.dart
  lib/main.dart
  lib/screens/not_found/not_found.dart
  lib/screens/splash_screen/components/wave_clipper.dart
  lib/screens/splash_screen/splash_screen.dart
  lib/widgets/rounded_wide_button.dart
  pubspec.lock
  pubspec.yaml
  test/widget_test.dart
Labels: enhancement, flutter

#15 Test Build for splash screen
  .github/workflows/detekt-analysis.yml
  README.md
  assets/fonts/Poppins-Bold.ttf
  assets/fonts/Poppins-BoldItalic.ttf
  assets/fonts/Poppins-Italic.ttf
  assets/fonts/Poppins-Regular.ttf
  assets/fonts/Righteous-Regular.ttf
  assets/images/logo.png
  lib/config/router.dart
  lib/config/theme.dart
  lib/data/account_repository.dart
  lib/logic/authentication/authentication_bloc.dart
  lib/logic/authentication/authentication_state.dart
  lib/main.dart
  lib/screens/not_found/not_found.dart
  lib/screens/splash_screen/components/wave_clipper.dart
  lib/screens/splash_screen/splash_screen.dart
  lib/widgets/rounded_wide_button.dart
  pubspec.lock
  pubspec.yaml
  test/widget_test.dart
Labels: apk-build

#16 Logo
  assets/images/logo.png
  assets/images/logo.svg
  lib/screens/splash_screen/splash_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#17 APK Build
  assets/images/logo.png
  assets/images/logo.svg
  lib/screens/splash_screen/splash_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: apk-build

#19 App localization
  analysis_options.yaml
  l10n.yaml
  lib/config/router.dart
  lib/config/theme.dart
  lib/data/repositories/account_repository.dart
  lib/l10n/app_en.arb
  lib/logic/authentication/authentication_bloc.dart
  lib/logic/authentication/authentication_state.dart
  lib/main.dart
  lib/screens/not_found/not_found.dart
  lib/screens/splash_screen/components/wave_clipper.dart
  lib/screens/splash_screen/splash_screen.dart
  lib/widgets/rounded_wide_button.dart
  pubspec.lock
  pubspec.yaml
  test/logic/authentication/authentication_bloc_test.dart
  test/widget_test.dart
Labels: enhancement, flutter

#21 Sign up
  analysis_options.yaml
  android/app/src/main/AndroidManifest.xml
  assets/images/Celebration.png
  assets/images/celebration.svg
  assets/images/party_hat.svg
  lib/config/constants/app_urls.dart
  lib/config/router.dart
  lib/config/routes/router.dart
  lib/config/themes/theme.dart
  lib/config/utils/typedefs.dart
  lib/core/authentication/bloc/authentication_bloc.dart
  lib/core/authentication/bloc/authentication_state.dart
  lib/core/authentication/models/user.dart
  lib/data/repositories/account_repository.dart
  lib/l10n/app_en.arb
  lib/main.dart
  lib/modules/not_found/screens/not_found.dart
  lib/modules/sign_up/bloc/sign_up_bloc.dart
  lib/modules/sign_up/bloc/sign_up_state.dart
  lib/modules/sign_up/components/form_field_decoration.dart
  lib/modules/sign_up/components/sign_up_wrapper.dart
  lib/modules/sign_up/models/sign_up_request.dart
  lib/modules/sign_up/models/sign_up_response.dart
  lib/modules/sign_up/pages/sign_up_complete.dart
  lib/modules/sign_up/pages/sign_up_one.dart
  lib/modules/sign_up/pages/sign_up_two.dart
  lib/modules/sign_up/providers/sign_up_provider.dart
  lib/modules/sign_up/repositories/sign_up_repository.dart
  lib/modules/splash_screen/screens/splash_screen.dart
  lib/utils/bloc_utils/bloc_form_field.dart
  lib/utils/ui_utils/wave_clipper.dart
  lib/widgets/custom_back_button.dart
  lib/widgets/gradient_widget.dart
  lib/widgets/rounded_wide_button.dart
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugins.cmake
  pubspec.lock
  pubspec.yaml
  test/logic/authentication/authentication_bloc_test.dart
Labels: enhancement, flutter, help wanted

#26 Sign up
  .gitignore
  lib/config/routes/router.dart
  lib/config/themes/theme.dart
  lib/config/utils/typedefs.dart
  lib/core/authentication/bloc/authentication_bloc.dart
  lib/core/authentication/models/user.dart
  lib/main.dart
  lib/modules/not_found/screens/not_found.dart
  lib/modules/sign_up/bloc/sign_up_bloc.dart
  lib/modules/sign_up/bloc/sign_up_state.dart
  lib/modules/sign_up/components/form_field_decoration.dart
  lib/modules/sign_up/components/sign_up_wrapper.dart
  lib/modules/sign_up/models/sign_up_response.dart
  lib/modules/sign_up/pages/sign_up_complete.dart
  lib/modules/sign_up/pages/sign_up_one.dart
  lib/modules/sign_up/pages/sign_up_two.dart
  lib/modules/sign_up/providers/sign_up_provider.dart
  lib/modules/sign_up/repositories/sign_up_repository.dart
  lib/modules/splash_screen/screens/splash_screen.dart
  lib/utils/bloc_utils/bloc_form_field.dart
  lib/utils/ui_utils/wave_clipper.dart
  lib/widgets/custom_back_button.dart
  lib/widgets/gradient_widget.dart
  lib/widgets/rounded_wide_button.dart
  pubspec.lock
  pubspec.yaml
  test/logic/authentication/authentication_bloc_test.dart
Labels: bug, enhancement, flutter

#27 Fix
  lib/modules/sign_up/bloc/sign_up_state.dart
  lib/modules/sign_up/components/form_field_decoration.dart
Labels: bug, flutter

#30 Signin imssurya
  cleanup.sh
  lib/config/routes/router.dart
  lib/constants/api_path.dart
  lib/constants/app_constants.dart
  lib/constants/asset_path.dart
  lib/core/authentication/authentication_bloc.dart
  lib/core/authentication/authentication_state.dart
  lib/data/signin_api_call.dart
  lib/gen/assets.gen.dart
  lib/gen/fonts.gen.dart
  lib/l10n/app_en.arb
  lib/modules/homepage/homepage.dart
  lib/modules/not_found/not_found.dart
  lib/modules/signin/cubit/siginin_cubit.dart
  lib/modules/signin/cubit/signin_state.dart
  lib/modules/signin/models/signin_reponse_model.dart
  lib/modules/signin/models/signin_request_model.dart
  lib/modules/signin/repositories/signin_repositiry.dart
  lib/modules/signin/screens/signinpage.dart
  lib/modules/splash_screen/components/wave_clipper.dart
  lib/modules/splash_screen/repositories/account_repository.dart
  lib/modules/splash_screen/splash_screen.dart
  pubspec.yaml
Labels: enhancement, flutter

#31 Sign In
  lib/config/constants/app_urls.dart
  lib/config/routes/router.dart
  lib/constants/api_path.dart
  lib/constants/app_constants.dart
  lib/constants/asset_path.dart
  lib/core/authentication/authentication_bloc.dart
  lib/core/authentication/authentication_state.dart
  lib/data/signin_api_call.dart
  lib/modules/home/screens/home.dart
  lib/modules/sign_in/cubit/siginin_cubit.dart
  lib/modules/sign_in/cubit/signin_state.dart
  lib/modules/sign_in/models/signin_reponse_model.dart
  lib/modules/sign_in/models/signin_request_model.dart
  lib/modules/sign_in/providers/sign_in_provider.dart
  lib/modules/sign_in/repositories/sign_in_repository.dart
  lib/modules/sign_in/screens/sign_in.dart
  lib/modules/sign_up/models/sign_up_request.dart
  lib/modules/sign_up/providers/sign_up_provider.dart
  lib/modules/sign_up/screens/sign_up_complete.dart
  lib/modules/sign_up/screens/sign_up_one.dart
  lib/modules/sign_up/screens/sign_up_two.dart
  lib/modules/signin/repositories/signin_repositiry.dart
  lib/modules/signin/screens/signinpage.dart
  lib/modules/splash_screen/screens/splash_screen.dart
  lib/modules/splash_screen/splash_screen.dart
  lib/widgets/form_field_decoration.dart
Labels: enhancement, flutter

#32 Verify email
  lib/config/constants/app_texts.dart
  lib/config/constants/app_urls.dart
  lib/config/routes/router.dart
  lib/config/themes/theme.dart
  lib/config/utils/extensions/int_extension.dart
  lib/config/utils/extensions/map_extension.dart
  lib/config/utils/extensions/response_extension.dart
  lib/core/authentication/bloc/authentication_bloc.dart
  lib/core/common/models/account_status_request.dart
  lib/core/common/models/account_status_response.dart
  lib/core/common/models/user.dart
  lib/core/common/providers/common_provider.dart
  lib/core/common/repositories/common_repository.dart
  lib/l10n/app_en.arb
  lib/main.dart
  lib/modules/sign_in/cubit/siginin_cubit.dart
  lib/modules/sign_in/models/signin_reponse_model.dart
  lib/modules/sign_in/providers/sign_in_provider.dart
  lib/modules/sign_in/repositories/sign_in_repository.dart
  lib/modules/sign_in/screens/sign_in.dart
  lib/modules/sign_up/bloc/sign_up_bloc.dart
  lib/modules/sign_up/bloc/sign_up_state.dart
  lib/modules/sign_up/models/sign_up_response.dart
  lib/modules/sign_up/providers/sign_up_provider.dart
  lib/modules/sign_up/repositories/sign_up_repository.dart
  lib/modules/sign_up/screens/sign_up_one.dart
  lib/modules/sign_up/screens/sign_up_two.dart
  lib/modules/splash_screen/screens/splash_screen.dart
  lib/modules/verify_email/bloc/verify_email_bloc.dart
  lib/modules/verify_email/bloc/verify_email_state.dart
  lib/modules/verify_email/components/otp_text_fields.dart
  lib/modules/verify_email/models/resend_otp_request.dart
  lib/modules/verify_email/models/resend_otp_response.dart
  lib/modules/verify_email/models/verify_email_request.dart
  lib/modules/verify_email/models/verify_email_response.dart
  lib/modules/verify_email/providers/verify_email_provider.dart
  lib/modules/verify_email/repositories/verify_email_repository.dart
  lib/modules/verify_email/screens/verification_complete.dart
  lib/modules/verify_email/screens/verify_email.dart
  lib/widgets/gradient_widget.dart
  lib/widgets/snackbar_message.dart
  lib/widgets/underlined_title.dart
  test/logic/authentication/authentication_bloc_test.dart
Labels: enhancement, flutter

#34 Fix
  lib/modules/not_found/not_found.dart
  lib/modules/sign_in/screens/sign_in.dart
  lib/modules/sign_up/bloc/sign_up_bloc.dart
  lib/modules/sign_up/screens/sign_up_one.dart
  lib/modules/sign_up/screens/sign_up_two.dart
  lib/modules/verify_email/bloc/verify_email_bloc.dart
  lib/modules/verify_email/screens/verification_complete.dart
  lib/modules/verify_email/screens/verify_email.dart
Labels: bug, flutter

#35 Sign in error
  lib/core/common/models/account_status_request.dart
  lib/core/common/models/account_status_response.dart
  lib/core/common/providers/common_provider.dart
  lib/l10n/app_en.arb
  lib/modules/sign_in/cubit/siginin_cubit.dart
  lib/modules/sign_in/cubit/signin_state.dart
  lib/modules/sign_in/providers/sign_in_provider.dart
  lib/modules/sign_in/screens/email_not_verified.dart
  lib/modules/sign_in/screens/sign_in.dart
  lib/modules/sign_up/providers/sign_up_provider.dart
  lib/modules/verify_email/providers/verify_email_provider.dart
  lib/widgets/form_field_decoration.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, flutter

#36 API Changes & Verification Redirection
  lib/config/constants/app_urls.dart
  lib/config/routes/router.dart
  lib/core/common/models/account_status_response.dart
  lib/modules/sign_in/cubit/siginin_cubit.dart
  lib/modules/sign_in/models/signin_reponse_model.dart
  lib/modules/sign_in/screens/email_not_verified.dart
  lib/modules/sign_in/screens/sign_in.dart
  lib/modules/sign_up/screens/sign_up_two.dart
  lib/modules/verify_email/bloc/verify_email_bloc.dart
  lib/modules/verify_email/bloc/verify_email_state.dart
  lib/modules/verify_email/models/resend_otp_request.dart
  lib/modules/verify_email/repositories/verify_email_repository.dart
  lib/modules/verify_email/screens/verify_email.dart
Labels: enhancement, flutter

#38 Fix
  lib/modules/sign_in/cubit/siginin_cubit.dart
Labels: bug, flutter

#43 Worker init
  assets/images/owner_username.svg
  assets/images/worker_name.svg
  lib/config/constants/app_urls.dart
  lib/config/routes/router.dart
  lib/core/authentication/bloc/authentication_bloc.dart
  lib/core/authentication/bloc/authentication_state.dart
  lib/core/common/models/account_status_response.dart
  lib/core/common/models/logout_request.dart
  lib/core/common/models/logout_response.dart
  lib/core/common/providers/common_provider.dart
  lib/core/common/repositories/common_repository.dart
  lib/l10n/app_en.arb
  lib/modules/home/screens/home.dart
  lib/modules/sign_in/cubit/siginin_cubit.dart
  lib/modules/sign_in/cubit/signin_state.dart
  lib/modules/sign_in/models/signin_reponse_model.dart
  lib/modules/sign_in/screens/email_not_verified.dart
  lib/modules/sign_in/screens/sign_in.dart
  lib/modules/splash_screen/components/wave_clipper.dart
  lib/modules/splash_screen/repositories/account_repository.dart
  lib/modules/splash_screen/screens/splash_screen.dart
  lib/modules/verify_email/bloc/verify_email_bloc.dart
  lib/modules/worker_initialize/bloc/worker_initialize_bloc.dart
  lib/modules/worker_initialize/bloc/worker_initialize_state.dart
  lib/modules/worker_initialize/models/worker_initialize_request.dart
  lib/modules/worker_initialize/models/worker_initialize_response.dart
  lib/modules/worker_initialize/providers/worker_initialize_provider.dart
  lib/modules/worker_initialize/repositories/worker_initialize_repository.dart
  lib/modules/worker_initialize/screens/worker_initialize.dart
  lib/widgets/form_field_decoration.dart
  pubspec.lock
  pubspec.yaml
  test/logic/authentication/authentication_bloc_test.dart
Labels: enhancement, flutter
